"""
Module: report.py

Project:
Earthquake Disaster Monitoring and Seismic Risk Analysis System

Description:
This module provides functionality for exporting earthquake risk
analysis results to a CSV file.

Functions:
export_risk_report():
Saves an earthquake risk assessment report as a CSV file.
"""

import os


def export_risk_report(report, output_file):
    """
    Export an earthquake risk report to a CSV file.

    Parameters:
        report (dict):
            Dictionary containing the results generated by
            EarthquakeAnalyzer.generate_risk_report().

        output_file (str):
            Path where the CSV report should be saved.

    Raises:
        KeyError:
            If the report does not contain a required result.

        OSError:
            If the output file cannot be created or written.
    """

    # Create the output directory.
    output_directory = os.path.dirname(output_file)

    if output_directory:
        os.makedirs(output_directory, exist_ok=True)

    try:
        with open(output_file, "w", encoding="utf-8") as file:

            # Write CSV column headings.
            file.write("Category,Value\n")

            # Write the main analysis results.
            file.write(
                f"Total Earthquakes Analyzed,"
                f"{report['Total Earthquakes']}\n"
            )

            file.write(
                f"Average Magnitude,"
                f"{report['Average Magnitude']}\n"
            )

            file.write(
                f"Strongest Magnitude,"
                f"{report['Strongest Magnitude']}\n"
            )

            file.write(
                f"Strongest Location,"
                f"{report['Strongest Location']}\n"
            )

            file.write(
                f"High Risk Earthquakes,"
                f"{report['High Risk Earthquakes']}\n"
            )

            # Write the earthquake frequency results.
            for category, count in report["Frequency"].items():
                file.write(
                    f"{category} Earthquakes,{count}\n"
                )

    except (KeyError, OSError) as error:
        raise OSError(
            f"Unable to export earthquake risk report: {error}"
        ) from error